"""update MediaCast model again

Revision ID: 3ddcf67961d5
Revises: b9677b3d7b78
Create Date: 2024-12-20 19:39:05.139849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddcf67961d5'
down_revision = 'b9677b3d7b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_casts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_media_actor_director', ['media_id', 'actor_director_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_casts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_media_actor_director', type_='unique')

    # ### end Alembic commands ###
