"""create a film genre table and set up relations

Revision ID: 4d08b8e63b63
Revises: 62c8232522f1
Create Date: 2024-12-22 13:39:42.862169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d08b8e63b63'
down_revision = '62c8232522f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_media_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['media_id'], ['media_types.id'], name=op.f('fk_media_genres_media_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_genres')
    # ### end Alembic commands ###
