"""create a user favourite genre model, and set up relations

Revision ID: 62c8232522f1
Revises: 3ddcf67961d5
Create Date: 2024-12-22 13:15:20.453457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c8232522f1'
down_revision = '3ddcf67961d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fave_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_user_fave_genre_genre_id_genres')),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], name=op.f('fk_user_fave_genre_user_id_accounts')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_fave_genre')
    # ### end Alembic commands ###
