"""initial migration

Revision ID: 7c988359f91d
Revises: 
Create Date: 2024-12-20 16:57:17.235556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c988359f91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('initial_sign_in', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('actor_director', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sub_title', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('cover_photo', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('run_time_hours', sa.Integer(), nullable=True),
    sa.Column('run_rime_minutes', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_types.id'], name=op.f('fk_tv_shows_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_shows')
    op.drop_table('media_types')
    op.drop_table('actors_directors')
    op.drop_table('accounts')
    # ### end Alembic commands ###
