"""create film cast table

Revision ID: b9677b3d7b78
Revises: 7c988359f91d
Create Date: 2024-12-20 19:18:26.832273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9677b3d7b78'
down_revision = '7c988359f91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_casts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('actor_director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_director_id'], ['actors_directors.id'], name=op.f('fk_media_casts_actor_director_id_actors_directors')),
    sa.ForeignKeyConstraint(['media_id'], ['media_types.id'], name=op.f('fk_media_casts_media_id_media_types')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_casts')
    # ### end Alembic commands ###
